name: CD Pipeline
on:  
  workflow_run:
    workflows: ["CI Pipeline"]    
    types:
      - completed
jobs:
  build:
    runs-on: self-hosted
    steps:    
    - name: Pull Docker image
      run: sudo docker pull Dimash26/cicd_m:latest    
    - name: Delete Old docker container
      run: sudo docker rm -f cicd-m-container || true    
    - name: Run Docker Container
      run: sudo docker run -d -p 80:3000 --name cicd-m-container Dimash26/cicd_m
