name: CI-CD via Self-Hosted Runner

on:
  push:
    branches: [ main ]
  # Optional: Uncomment if you want to run on pull requests as well
  # pull_request:
  #   branches: [ main ]

jobs:
  build-and-deploy:
    # This tells GitHub Actions to use a self-hosted runner
    # that you've set up. The runner must have at least the
    # 'self-hosted' label. If your runner is labeled differently,
    # adjust accordingly.
    runs-on: self-hosted
    # If you used additional labels, for example 'ec2', use:
    # runs-on: [self-hosted, ec2]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t hello-world-app:latest .

      - name: Stop and remove old container
        run: |
          docker rm -f hello-world || true

      - name: Run new container
        run: |
          # Run the new container on port 3000
          # Adjust the port or name as needed
          docker run -d --name hello-world -p 3000:3000 hello-world-app:latest
